#
# ~/nixos-config/hosts/boreal/configuration.nix
#
# =============================================================================
# HOST CONFIGURATION: boreal (x86_64, production)
# =============================================================================
# Thin host entrypoint for the boreal host.
# Imports host-local modules for boot, graphics, storage, networking, users,
# and host-specific service values.
#
# TO ADD A NEW HOST:
# 1. Create directory: hosts/<hostname>/
# 2. Copy this file to hosts/<hostname>/configuration.nix
# 3. Split host-local concerns into additional files as needed
#    (for example: base.nix, graphics.nix, storage.nix, users.nix).
# 4. Register the host in the `hosts` attrset in flake.nix.
# 5. Add one or more `outputDefs` entries for the profiles you want.
#
# HARDWARE-CONFIGURATION.NIX:
#   This file is auto-generated by NixOS during installation.
#   Contains disk UUIDs, partition layout, and hardware detection.
#   DO NOT copy to new hosts - let NixOS generate it fresh.
# =============================================================================
#
{...}: {
  imports = [
    ./hardware-configuration.nix
    ./base.nix
    ./graphics.nix
    ./storage.nix
    ./networking.nix
    ./users.nix
    ./services.nix
  ];

  # See: https://nixos.org/manual/nixos/stable/options#opt-system.stateVersion
  system.stateVersion = "25.11";
}
