#
# ~/nixos-config/modules/home/nvim-theme.nix
#
# Neovim theme selector module.
# Select a theme via my.nvimTheme option (e.g., "gars-yellow-dark").
# Available themes are in ./themes/nvim/ directory.
#
{
  config,
  pkgs,
  ...
}: let
  # Available themes in ./themes/nvim/
  availableThemes = {
    "gars-yellow-dark" = ./themes/nvim/gars-yellow-dark.lua;
    "gars-yellow-light" = ./themes/nvim/gars-yellow-light.lua;
  };
in {
  config = {
    # Copy both theme files to nvim colors directory
    home.file.".config/nvim/colors/gars-yellow-dark.lua".source = availableThemes."gars-yellow-dark";
    home.file.".config/nvim/colors/gars-yellow-light.lua".source = availableThemes."gars-yellow-light";

    # Generate theme loader that picks the selected theme
    home.file.".config/nvim/lua/config/theme.lua".source = pkgs.writeText "nvim-theme.lua" ''
      -- Auto-generated by NixOS configuration
      vim.cmd.colorscheme("${config.my.nvimTheme}")
    '';
  };
}
