#
# ~/nixos-config/modules/home/nvim-theme.nix
#
# Neovim theme selector module.
# Select a theme via my.nvimTheme option (e.g., "gars-yellow-dark").
# Available themes are in ./themes/nvim/ directory.
#
{
  config,
  pkgs,
  lib,
  ...
}: let
  # Available themes in ./themes/nvim/
  availableThemes = {
    "gars-yellow-dark" = ./themes/nvim/gars-yellow-dark.lua;
    "gars-yellow-light" = ./themes/nvim/gars-yellow-light.lua;
  };

  # Copy theme files to actual ~/.config/nvim/colors (not the symlinked repo dir)
  copyThemesScript = pkgs.writeShellScriptBin "nvim-copy-themes" ''
    #!/usr/bin/env bash
    DEST_DIR="$HOME/.config/nvim/colors"
    mkdir -p "$DEST_DIR"
    cp ${availableThemes."gars-yellow-dark"} "$DEST_DIR/gars-yellow-dark.lua"
    cp ${availableThemes."gars-yellow-light"} "$DEST_DIR/gars-yellow-light.lua"
    echo "Neovim themes copied to $DEST_DIR"
  '';

  themeScript = pkgs.writeShellScriptBin "nvim-set-theme" ''
      #!/usr/bin/env bash
      THEME="${config.my.nvimTheme}"
      DEST="$HOME/.config/nvim/lua/config/theme.lua"
      mkdir -p "$(dirname "$DEST")"
      cat > "$DEST" <<EOF
    -- Auto-generated by NixOS configuration
    vim.cmd.colorscheme("$THEME")
    EOF
      echo "Neovim theme set to: $THEME"
  '';
in {
  config = {
    # Install the scripts
    home.packages = [copyThemesScript themeScript];

    # Run scripts on activation
    home.activation.setNvimTheme = lib.hm.dag.entryAfter ["writeBoundary"] ''
      $DRY_RUN_CMD ${copyThemesScript}/bin/nvim-copy-themes
      $DRY_RUN_CMD ${themeScript}/bin/nvim-set-theme
    '';
  };
}
