[colors.primary]
background = "#1e1904"
foreground = "#f6eec9"
dim_foreground = "#a29c7f"
bright_foreground = "#fcf9e8"

[colors.cursor]
text = "#3b3724"
cursor = "#efdd84"

[colors.vi_mode_cursor]
text = "#3b3724"
cursor = "#e3c220"

[colors.search.matches]
foreground = "#1e1904"
background = "#b7b193"

[colors.search.focused_match]
foreground = "#1e1904"
background = "#e3c220"

[colors.footer_bar]
foreground = "#1e1904"
background = "#b7b193"

[colors.hints.start]
foreground = "#1e1904"
background = "#e3c220"

[colors.hints.end]
foreground = "#1e1904"
background = "#a29c7f"

[colors.selection]
text = "#1e1904"
background = "#efdd84"

[colors.normal]
black = "#322f1f"
red = "#ef8484"
green = "#e4ef84"
yellow = "#e3c220"
blue = "#84baef"
magenta = "#f4b8e4"
cyan = "#84e0ef"
white = "#ded7b4"

[colors.bright]
black = "#3b3724"
red = "#ef8484"
green = "#e4ef84"
yellow = "#efdd84"
blue = "#84baef"
magenta = "#ef84ac"
cyan = "#84e0ef"
white = "#cbc4a3"

[[colors.indexed_colors]]
index = 16
color = "#ef9f76"

[[colors.indexed_colors]]
index = 17
color = "#f8ebac"

