[general]
import = [
  "~/.config/alacritty/themes/gars-yellow.toml"
]

[font]
size = 11.0

[font.normal]
family = "Roboto Mono"
style = "Regular"

[font.bold]
family = "Roboto Mono"
style = "Bold"

[font.italic]
family = "Roboto Mono"
style = "Italic"

[font.bold_italic]
family = "Roboto Mono"
style = "Bold Italic"

[window]
padding = { x = 4, y = 4 }
